### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Sascha89** [eventerza/eventerza#2]
On triggering such php artisan commands, permission denied errors are responded:

example:
docker exec -it eventerza_php_1 bash -c 'php artisan make:auth'

Result:
[ErrorException]            
  mkdir(): Permission denied

**Comment by mc388** [comment]
This is because the docker user (www-data) has no permissions to create folders in your folder.

You have 2 options:
1. run this command locally without docker
2. add your user to www-data group (id 33) and set the file owner to www-data and try it again

I would prefer option 1 because locally you have php installed

**Comment by Sascha89** [comment]
Ok. But I thought this would be a big advantage of docker, that I won't need a local php anymore ;)

**Comment by mc388** [comment]
If you want to use docker without php locally you need to change some permissions. From my point of view the big advantage of docker is that you run the same environment on dev and prod and you don't need php on prod.
If you want no php locally then you also need a composer container.
